### ISSUE TITLE
I can't acces to Download the OpenI image features from our BioNLP server to test Medical Image Retrieval via Nearest Neighbor Search on Pre-trained Image Features

### ISSUE THREAD

**Issue by mohanajjar** [deepaknlp/DLS#1]
Dear  deepaknlp.
I hope this message finds you well. I wanted to express my sincere appreciation for the incredible work you've shared . Your contributions have been invaluable, and I've learned a great deal from your projects.

I'm currently exploring the same topic but with extracting 3D medical images features , and I've encountered a small hurdle. Unfortunately, to experiment SearchAndIndexingJavaCode I'm unable to access image features [BioNLP server](https://bionlp.nlm.nih.gov/features/openi/) , Forbidden message displays when i try to access. 
I believe your expertise could greatly assist me in overcoming this challenge.

### I understand that your time is valuable, and I'm more than willing to compensate you for your assistance. Please let me know if you'd be open to discussing this further. I'm eager to resolve this issue and continue benefiting from your expertise.

I'm reachable at : espoirmone@yahoo.com

**Comment by medvidqa** [comment]
Here are the  links:

https://bionlp.nlm.nih.gov/features/openi/resnet50_conv5block1_2conv_tf2/train_images.txt
https://bionlp.nlm.nih.gov/features/openi/resnet50_conv5block1_2conv_tf2/train.txt

https://bionlp.nlm.nih.gov/features/openi/resnet50_conv5block1_2conv_tf2/test_images.txt
https://bionlp.nlm.nih.gov/features/openi/resnet50_conv5block1_2conv_tf2/test.txt

https://bionlp.nlm.nih.gov/features/openi/convnext_large_in22k/train_images.txt
https://bionlp.nlm.nih.gov/features/openi/convnext_large_in22k/train.txt

https://bionlp.nlm.nih.gov/features/openi/convnext_large_in22k/test_images.txt
https://bionlp.nlm.nih.gov/features/openi/convnext_large_in22k/test.txt

**Comment by deepaknlp** [comment]
Here are the links:

https://bionlp.nlm.nih.gov/features/openi/resnet50_conv5block1_2conv_tf2/train.txt
https://bionlp.nlm.nih.gov/features/openi/resnet50_conv5block1_2conv_tf2/test.txt

https://bionlp.nlm.nih.gov/features/openi/convnext_large_in22k/train.txt
https://bionlp.nlm.nih.gov/features/openi/convnext_large_in22k/test.txt
